version: "3"
services:
# it's nothing more than a container
# for 4 services - define 4 containers
# we building api "container" and "postgres"
  api:
    image: monolith651/fastapi2_api
    # we basically executing command $docker build -t api .
    # so the docker compose will auto build image for us
    # with current directory . as docker-compose.yml file
    depends_on:
      - postgres
    ports:
      - 80:8000
      # expect array of ports
      # <port on localhost>:<port on container>
    volumes:
      - ./:/usr/src/app:ro
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000 

#     # env_file:
#     #     - ./.env
    environment:
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: